### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by btjanaka** [Rochan-A/gym-dino#1]
Hi @Rochan-A, this is an awesome project! I may be interested in using it for my work. What is the license for it? Thanks!

**Comment by Rochan-A** [comment]
Hi @btjanaka, glad the project could help you. Since most of the code is inherited from https://github.com/shivamshekhar/Chrome-T-Rex-Rush project, I have added the MIT License. Hope this is helpful! Thanks!

**Comment by btjanaka** [comment]
Thanks!
